sudo: required
env:
  global:
  - DOCKER_USER=boynux
  - secure: JEL+fVC7tZZGHDHfVG0WQWyU6K93zRNOLB5ioBlfzGw9nQHY01EtW1WYFAPS6wvrL8wggIk9MZ5rIm4xHlvY+8BAXv4IyhhWnfTWInQaBVxh+LhfzrE0cSriK69NSbuSUlwIcKypSy9HtkIyq1iposep1UM3RNsaAW4IIJSm+qio5nE2sRAxcptfcTwCfxIJvQt7r0UaqzkSU77gE4TZUepd2ZBC5gz3Qs5rqvimGi6UDrNnxrwYg0xVAEZhg7ph5WVbHA36dyMoZ3kQASYQWg6spyLz1loLSZ4EO7dvA8r6xTjkVpboqVTL4sUZMeaEcbQNBNxl6iAUHmOTeOafvlgQnYawxThcO2A7cFdGRWXAMGDujPYhvFiqA59V2C9mzSY9MRb1N9iKU3xDiPz+T9jHUyYvEglOyTGx0OL4uNWUxYYstTVk+wGbVMlXAmFlLBo2QqE8Sqx/DgnqUVl/nDacY+jTRHBbXxj/xIsNHG2wSBcQoPYeCI38rinfV1YTWbSncqxdSgum77QOdryfNi5PCxZShUd4zRV9xOPi4GHdxCc1QINGt/OjoMKe2BuFPGDr9QBD4Ftu+b0sx6Xz0QF4/d4ZVyvJH64mJiADRYySCz3QPPd3JdaoK76V9ltuIZVuIrQQBbI7lUNkRpseMsdUXH7A/je7GssOkkfoh5o=
services:
- docker
language: bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t boynux/daastani .
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
    TAG="armhf-$TRAVIS_BUILD_NUMBER"
    docker tag hypriot/rpi-mysql boynux/daastani:$TAG
    docker push boynux/daastani:$TAG
    docker push boynux/daastani
  fi
