# theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
title: Daastani
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      
repository: "boynux/daastani"
search: true

