# theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
title: Daastani
teaser: /assets/images/500x300.png

defaults:
  - scope:
      path: ""
    values:
      layout: single
      # classes: wide
      toc: true
      author_profile: true
      
author:
  name: "Daastani"
  avatar: "https://raw.githubusercontent.com/boynux/daastani/master/docs/assests/images/sheep.png"
  bio: "Story box"
      
repository: "boynux/daastani"
search: true

